/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmployeeRecord = IDL.Record({
  'id' : IDL.Nat,
  'bankAccountNumber' : IDL.Opt(IDL.Text),
  'ifscCode' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'mobileNumber' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Nat,
  'aadhaarNumber' : IDL.Opt(IDL.Text),
  'uanNumber' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([EmployeeRecord], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(EmployeeRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [EmployeeRecord], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateEmployee' : IDL.Func([IDL.Nat, EmployeeRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmployeeRecord = IDL.Record({
    'id' : IDL.Nat,
    'bankAccountNumber' : IDL.Opt(IDL.Text),
    'ifscCode' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'mobileNumber' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Nat,
    'aadhaarNumber' : IDL.Opt(IDL.Text),
    'uanNumber' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([EmployeeRecord], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(EmployeeRecord)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [EmployeeRecord], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateEmployee' : IDL.Func([IDL.Nat, EmployeeRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };