/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmployeeRecord {
  'id' : bigint,
  'bankAccountNumber' : [] | [string],
  'ifscCode' : [] | [string],
  'name' : string,
  'mobileNumber' : [] | [string],
  'employeeId' : [] | [string],
  'timestamp' : bigint,
  'aadhaarNumber' : [] | [string],
  'uanNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<[EmployeeRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<EmployeeRecord>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[bigint], EmployeeRecord>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateEmployee' : ActorMethod<[bigint, EmployeeRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];